#pragma once

#include <absl/container/btree_map.h>
#include <absl/container/btree_set.h>
#include <absl/container/flat_hash_map.h>
#include <absl/container/flat_hash_set.h>
#include <absl/container/inlined_vector.h>
#include <absl/functional/function_ref.h>
#include <absl/strings/match.h>
#include <absl/strings/str_cat.h>
#include <absl/strings/string_view.h>
#include <absl/types/span.h>
#include <absl/types/variant.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <bit>
#include <boost/circular_buffer.hpp>
#include <boost/intrusive/list.hpp>
#include <boost/intrusive/list_hook.hpp>
#include <boost/iterator/iterator_facade.hpp>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <limits>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#include "base/flags.h"
#include "base/io_buf.h"
#include "base/logging.h"
#include "base/spinlock.h"
#include "core/compact_object.h"
#include "core/detail/stateless_allocator.h"
#include "core/mi_memory_resource.h"
#include "core/small_string.h"
#include "util/fibers/fibers.h"
#include "util/fibers/synchronization.h"
